### ISSUE TITLE
Add LICENSE file?

### ISSUE THREAD

**Issue by mithro** [georgerennie/Matt_Venn_q3k_TPM2137_Solution#1]
Would you mind adding a LICENSE file?
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by georgerennie** [comment]
Sure, I've made it BSD-3 (although the code is very much of hacky ctf quality haha, in particular the bits like interfacing with iverilog arent very robust)
